const express = require("express");
const router = express.Router();
const controller = require("../controllers/conda");
router.post("/fastqc", controller.runFastqc);
router.post("/indexh", controller.runIndexh);
router.post("/indexp", controller.runIndexp);
router.post("/checkg", controller.checkGenome);
router.post("/qc", controller.runQc);
router.post("/dbsub", controller.runDbsub);
router.post("/gncons", controller.runGenCons);
router.post("/gncons1", controller.runGenCons1);
router.post("/gncons2", controller.runGenCons2);
router.post("/gncons3", controller.runGenCons3);
router.post("/gncons4", controller.runGenCons4);
router.post("/gncons5", controller.runGenCons5);
router.post("/redbsub", controller.rerunDbsub);
router.post("/pipe", controller.runPipe);
router.get("/seqkit", controller.runseqkit);
//router.get("/conda/:folder", controller.getListFiles);
//router.get("/conda/:name", controller.download);
module.exports = router;